export const articles = [
  {
    id: 1,
    title: "ニュースタイトル",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "news",
  },
  {
    id: 2,
    title: "ニュースタイトル",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "news",
  },
  {
    id: 3,
    title: "ニュースタイトル",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "news",
  },
  {
    id: 4,
    title: "ニュースタイトル",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "news",
  },
  {
    id: 5,
    title: "ニュースタイトル",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "news",
  },
  {
    id: 6,
    title: "プレスリリース",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "press",
  },
  {
    id: 7,
    title: "プレスリリース",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "press",
  },
  {
    id: 4,
    title: "プレスリリース",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "press",
  },
  {
    id: 5,
    title: "プレスリリース",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "press",
  },
  {
    id: 6,
    title: "プレスリリース",
    content: "テキストテキストテキストテキスト",
    date: new Date("2023-07-07"),
    genre: "press",
  },
];
